name: Build & Deploy

on:
  push:
    branches: [ "main" ]

  pull_request:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php-version: [8.0]

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up PHP ${{ matrix.php-version }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          extensions: mbstring, mysqli, zip, gd
          coverage: none

      - name: Install Composer
        run: composer install --no-dev --optimize-autoloader

      - name: Run Tests
        run: vendor/bin/phpunit --configuration phpunit.xml

      - name: Build Project (if needed)
        run: |
          # Add any build steps if necessary. For CodeIgniter 3, this might not be required.

      - name: Create deployment archive
        uses: a7ul/tar-action@v1.1.0
        with:
          command: c
          cwd: "./"
          files: |
            application/
            system/
            user_guide/
            index.php
            captain-definition
          outPath: deploy.tar

      - name: Deploy App to CapRover
        uses: caprover/deploy-from-github@v1.0.1
        with:
          server: '${{ secrets.CAPROVER_SERVER }}'
          app: 'www'
          token: '${{ secrets.APP_TOKEN }}'
